### ISSUE TITLE
can't use custom font

### ISSUE THREAD

**Issue by rayjun83** [codegeeker180/AVFonts#4]
i have custom font configed in info.plist like below:
<key>UIAppFonts</key>
<array>
	<string>Canada Type - Gibson-Bold.otf</string>
	<string>Canada Type - Gibson-BoldItalic.otf</string>
	<string>Canada Type - Gibson-Italic.otf</string>
	<string>Canada Type - Gibson-Light.otf</string>
	<string>Canada Type - Gibson-SemiboldIt.otf</string>
	<string>Canada Type - Gibson-SemiBold.otf</string>
	<string>Canada Type - Gibson-Regular.otf</string>
	<string>Canada Type - Gibson-LightIt.otf</string>
</array>

code:
AVFonts.changeFont(toFont: "Gibson-Bold")

but console output: You entered an invalid Font Name .Please check your font name

not support custom font?

**Comment by kamalkbhardwaj** [comment]
I have doubt that font hasn't added properly. 
Please try this in AppDelegate 
print(UIFont.familyNames)

and confirm if custom font family has been added or not.

**Comment by rayjun83** [comment]
you are right, my otf files are not added to project correctly, after i have done right, everything is OK
